apiVersion: v1
kind: Service
metadata:
  name: flask-backend-service
spec:
  selector:
    app: flask-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001  # Redirect traffic to Flask's container port
  type: LoadBalancer  # Use LoadBalancer if you want to expose it outside (in Minikube use NodePort)
