apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  selector:
    app: react-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Redirect traffic to React's container port
  type: LoadBalancer  # Use LoadBalancer if you want to expose it outside (in Minikube use NodePort)
