name: CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  deploy-to-k8s:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/mlops-project:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Deploy to Minikube
      run: |
        # Apply deployment and service YAML files
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

